### ISSUE TITLE
Kaj je poteza?

### ISSUE THREAD

**Issue by andrejbauer** [kristjankostelec/ProjectLess#2]
Če prav razumem, je ena poteza za vaju **par lokacij** (od kod gre ploščica in kam). Vendar pa nikjer nimata razreda, s katerim bi lahko predstavila eno potezo. Posledice za kodo so negativne:

* v `Igra.narediPotezo` sprejmeta dve lokaciji namesto ene poteze.
* v `Minimax.minimax` se čara tako, da se gre po figuricah in potem po potezah za figurico, namesto da bi se šlo po potezah.
* potem se v `OcenjenaPoteza` spet dela z dvema lokacijama.

Predlagam, da definirata razred `Poteza`, ki vsebuje dve lokaciji in ustrezno popravita kodo. Predvsem definirajta metodo `moznePoteze`, ki vrne *vse* možne poteze. Ganartiram, da bo koda lepša in krajša.

**Comment by andrejbauer** [comment]
Glavni kaos je pa prav v minimaxu, v metodi `doInBackground`. Ker nimata razreda `Poteza`, si shranjujeta začetno lokacijo v `this.zacetna` in jo potem "prešvercata" na tak način v metodo `done`, ta pa `get()` dobi še končno lokacijo. To je **zelo grdo** in je treba nujno popraviti, ker ne spoštuje protokola za uporabo `SwingWorker`.

Zaenkrat pa ugotavljam, zakaj se vajin minimax kliče vedno znova, namesto da bi se samo enkrat.

**Comment by andrejbauer** [comment]
`Minimax` bi moral imeti `extends SwingWorker<OcenjenaPoteza, Object>` in ne tako kot je zdaj `extends SwingWorker<Lokacija,Object>`.

**Comment by kristjankostelec** [comment]
Implementacijo sem naredil v b9593e31ff914cd8cfa0b70cbf43660558b28663. 
Potem so nastale napake, ki jih zdaj iščem. Treba je preveriti, kdo napačno sporoči, katere poteze so veljavne.

**Comment by Tejchy85** [comment]
Kar sem na hitro pogledala, mislim da je problem v tem, da nimamo še definirane funkcije equals za Potezo  in se zato pojavijo problemi pri contains.

**Comment by Tejchy85** [comment]
Funkcija mozne poteze in veljavna poteza delujejo. Sem jih stestirala v TestIgra.
