### ISSUE TITLE
Metoda `Igra.narediPotezo` naj vrača `boolean`

### ISSUE THREAD

**Issue by andrejbauer** [kristjankostelec/ProjectLess#3]
Metoda `narediPotezo` v `Igra` naj vrača boolean, in sicer `true`, če se je poteza uspešno izvedla. To se potem uporabi v `GlavnoOkno.odigraj`. Namreč, če se metoda `odigraj` v `GlavnoOkno` pokliče na neveljavni potezi, potem se ne sme še enkrat na strategu klicati `na_potezi()`.

Problem, ki ga imata je naslednji: nekaj je narobe z metodo `odigraj`, ali pa z `minimax`, ne vemo. Vemo pa (če poženetda debugger), da računalnik poskuša neprestano delati isto potezo. To se zgodi zato, ker `GlavnoOkno.odigraj` ne naredi poteze, potem pa `GlavnoOkno.odigraj` neprestano kliče stratega na eni in isti poziciji.

V programu je treba najprej narediti malo več reda, potem bomo pa imeli šanso, da najdemo napako. Trenutno sploh ni problem napaka, ampak to, da je program tako zaštrikan, da napake sploh ne moremo iskati.

**Comment by andrejbauer** [comment]
Ko bosta odpravila vse issue, ki sem jih odprl, pa je treba pogledati, ali `Igra.narediPotezo` deluje pravilno, oziroma, zdi se da `Igra.veljavnaPoteza` ne dela pravilno, ker trdi, da so nekatere veljavne poteze (ki jih izračuna minimax) neveljavne. Ampak najprej kodo spraviti v red, prosim.

**Comment by kristjankostelec** [comment]
Issue je bil razrešen hkrati s popravljanjem minimax v 7bce643a612a8f89b3fe837439951de945ee737a.
