### ISSUE TITLE
Odstrani `.project` in `.classpath` iz glavne mape

### ISSUE THREAD

**Issue by andrejbauer** [kristjankostelec/ProjectLess#4]
Ker sicer Eclipse misli, da sta dva projekta v repozitoriju.

**Comment by Tejchy85** [comment]
Issue je bil razrešen v commitu skupaj z začetkom dela po govorilni 
https://github.com/kristjankostelec/ProjectLess/commit/aecbb0eb28edba83488c68b05273ce286fb8cac5.
